disable ingress to test deploy
procore/atlantis-helm-chart pull request #3
Opened 2021-03-17 19:24 UTC by rarkebauer

2021-04-27 17:37 UTC, edanc approved these changes

2021-04-27 17:38 UTC, MFeuerborn approved these changes

2021-04-27 19:39 UTC, kespinola requested changes
Since it's not supporting istio at this time I advocate from removing it from the PR so the service type LoadBalancer is the focus.

2021-04-27 20:27 UTC, rarkebauer commented
> Since it's not supporting istio at this time I advocate from removing it from the PR so the service type LoadBalancer is the focus.

that's fair, I've updated the PR to remove all istio references

2021-04-28 14:39 UTC, kespinola commented on charts/atlantis/stages/production/values.yaml
> +  type: LoadBalancer
https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support

I was reading through the docs on load balancer source range and requires the use of an nlb when using the default externalTrafficPolicy of cluster.

In order to provision and nlb extra annotation is required.

```
  service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

2021-04-28 15:16 UTC, kespinola approved these changes

2021-04-28 15:34 UTC, edanc approved these changes

2021-04-28 17:05 UTC, merged