Add GitHub app
procore/atlantis-helm-chart pull request #7
Opened 2021-05-04 00:08 UTC by tom-mckay

2021-05-04 13:07 UTC, rarkebauer requested changes

2021-05-04 13:07 UTC, rarkebauer commented on charts/atlantis/stages/production/values.yaml
> +  ATLANTIS_GH_APP_ID: 113650
```suggestion
  ATLANTIS_GH_APP_ID: 113131
```

2021-05-04 13:07 UTC, rarkebauer commented on charts/atlantis/stages/production/values.yaml
> +        - key: github_app_key_file
```suggestion
        - key: github_key_file
```

2021-05-04 13:07 UTC, rarkebauer commented on charts/atlantis/stages/staging/values.yaml
> +        - key: github_app_key_file
```suggestion
        - key: github_key_file
```

2021-05-04 13:35 UTC, tom-mckay commented on charts/atlantis/stages/production/values.yaml
> +        - key: github_app_key_file
We were trying to keep the names of the keys in the secret somewhat aligned with the names of the environment variables they're used in. I'd actually prefer `atlantis_gh_app_key_file` for this one.

2021-05-05 23:24 UTC, brandonpollard approved these changes
lgtm

2021-05-06 12:54 UTC, rarkebauer approved these changes

2021-05-06 14:41 UTC, merged